git
vim --with-python3 --with-python --with-lua
llvm --with-clang
tig
tmux
reattach-to-user-namespace
ansible
ag
peco
mas
mercurial
ctags
mongodb
redis
roswell
jq
khell/homebrew-srm/srm
brew-cask
ethereum
geth
openssl
doxygen
graphviz
wget
jq
